name: super_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

# Dart SDK and Flutter environment constraints
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth_mocks: ^0.14.1

# To resolve version conflicts if any
dependency_overrides:
  firebase_storage_web: ^3.6.22

flutter:
  # Use Material Design icons
  uses-material-design: true

  # Asset management
  assets:
    - assets/shoes/airforce.jpg
    - assets/shoes/timberland.jpg
    - assets/shoes/converse.jpg
    - assets/shoes/airmax.jpg
    - assets/happy.jpg
    - assets/uber-cabs-1024x576.webp
    - assets/Queens-Tavern-Steak.jpg

# Additional comments:
# - Use `flutter pub upgrade --major-versions` to ensure all dependencies are updated to the latest compatible versions.
# - To clean and rebuild the project, run `flutter clean` followed by `flutter pub get`.
